name: tmdbmaze
description: "Exploring TV shows from the TV Maze API"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.0.5
  http: ^1.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
